import { act, cleanup, fireEvent, render, screen } from '@testing-library/react'
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import { EditorView } from '@codemirror/view'
import { VisualEditor } from '@/components/editor/visual-editor'
import { useEditorStore } from '@/lib/store'

const wrap=(body:string)=>`\\documentclass{article}\n% Preserve my preamble.\n\\begin{document}\n${body}\n\\end{document}\n`
const view=(container:HTMLElement)=>EditorView.findFromDOM(container.querySelector('.cm-editor')!)!
beforeEach(()=>{
  HTMLElement.prototype.scrollIntoView=vi.fn()
  Range.prototype.getClientRects=vi.fn(()=>[] as unknown as DOMRectList)
  Range.prototype.getBoundingClientRect=vi.fn(()=>new DOMRect())
  useEditorStore.setState({content:'Hello world.',savedContent:'Hello world.',activeFilePath:'one.tex',workspaceRoot:'test',isModified:false,isNavigating:false,pendingDraft:null})
  useEditorStore.getState().resetSourceHistory()
})
afterEach(cleanup)

describe('continuous visual document',()=>{
  it('publishes typing synchronously and preserves source outside the edit',()=>{
    const original=wrap('An \\emph{original} phrase.\n\nSecond paragraph.\n\\custom{untouched}')
    useEditorStore.setState({content:original})
    const result=render(<VisualEditor/>),editor=view(result.container),from=original.indexOf('Second')
    act(()=>editor.dispatch({changes:{from,to:from+6,insert:'Edited'}}))
    result.unmount()
    expect(useEditorStore.getState().content).toBe(original.replace('Second','Edited'))
  })
  it('undoes and redoes through the shared store across mode switches',()=>{
    const first=render(<VisualEditor/>),editor=view(first.container)
    act(()=>editor.dispatch({changes:{from:0,to:5,insert:'Changed'}}))
    first.unmount();const second=render(<VisualEditor/>)
    fireEvent.click(screen.getByTitle('Undo'))
    expect(view(second.container).state.doc.toString()).toBe('Hello world.')
    fireEvent.click(screen.getByTitle('Redo'))
    expect(view(second.container).state.doc.toString()).toBe('Changed world.')
  })
  it('maps the caret for external agent changes without duplicate history entries',()=>{
    const result=render(<VisualEditor/>),editor=view(result.container)
    act(()=>editor.dispatch({selection:{anchor:5}}))
    act(()=>useEditorStore.getState().setContent('New Hello world.'))
    expect(view(result.container)).toBe(editor)
    expect(editor.state.doc.toString()).toBe('New Hello world.')
    expect(editor.state.selection.main.anchor).toBe(9)
    act(()=>useEditorStore.getState().undo())
    expect(editor.state.doc.toString()).toBe('Hello world.')
    expect(useEditorStore.getState().canUndo).toBe(false)
  })
  it('resets the editor for another file with identical content',()=>{
    const result=render(<VisualEditor/>),editor=view(result.container)
    act(()=>editor.dispatch({changes:{from:0,to:5,insert:'Changed'}}))
    act(()=>{useEditorStore.setState({activeFilePath:'two.tex'});useEditorStore.getState().resetSourceHistory()})
    expect(view(result.container)).not.toBe(editor)
    expect(screen.getByTitle('Undo')).toBeDisabled()
  })
  it('formats across paragraphs as separate valid TeX arguments',()=>{
    useEditorStore.setState({content:wrap('First paragraph.\n\nSecond paragraph.')})
    const result=render(<VisualEditor/>),editor=view(result.container),source=editor.state.doc.toString()
    act(()=>editor.dispatch({selection:{anchor:source.indexOf('First'),head:source.indexOf('\n\\end')}}))
    fireEvent.click(screen.getByTitle('Bold (Ctrl+B)'))
    expect(useEditorStore.getState().content).toBe(wrap('\\textbf{First paragraph.}\n\n\\textbf{Second paragraph.}'))
  })
  it('uses one editing surface without rewriting macros on focus',()=>{
    const original=wrap('An \\emph{original} phrase with \\custom{data}.')
    useEditorStore.setState({content:original})
    const result=render(<VisualEditor/>)
    expect(result.container.querySelectorAll('[contenteditable=true]')).toHaveLength(1)
    act(()=>view(result.container).focus())
    expect(useEditorStore.getState().content).toBe(original)
  })
  it('inserts menu commands into the body',()=>{
    useEditorStore.setState({content:wrap('Hello.')})
    render(<VisualEditor/>)
    act(()=>window.dispatchEvent(new CustomEvent('editor:command',{detail:{command:'insert',text:'\\section{Inserted}\n'}})))
    expect(useEditorStore.getState().content).toBe(wrap('\\section{Inserted}\nHello.'))
  })
  it('preserves document boundaries when replacing Select All through Insert',()=>{
    const source=wrap('Hello.')
    useEditorStore.setState({content:source})
    const result=render(<VisualEditor/>),editor=view(result.container)
    act(()=>editor.dispatch({selection:{anchor:0,head:source.length}}))
    fireEvent.pointerDown(screen.getByRole('button',{name:'Insert'}),{button:0,ctrlKey:false,pointerType:'mouse'})
    fireEvent.click(screen.getByRole('menuitem',{name:'Symbol'}))
    fireEvent.click(screen.getByRole('button',{name:'Apply'}))
    expect(useEditorStore.getState().content).toMatch(/^\\documentclass\{article\}\n% Preserve my preamble\.\n\\begin\{document\}/)
    expect(useEditorStore.getState().content).toMatch(/\\end\{document\}\n$/)
  })
  it('rejects a dialog selection crossing concealed formatting',()=>{
    const source=wrap('A \\textbf{bold phrase} after.')
    useEditorStore.setState({content:source})
    const result=render(<VisualEditor/>),editor=view(result.container)
    act(()=>editor.dispatch({selection:{anchor:source.indexOf('phrase'),head:source.indexOf('after')+5}}))
    fireEvent.pointerDown(screen.getByRole('button',{name:'Insert'}),{button:0,ctrlKey:false,pointerType:'mouse'})
    fireEvent.click(screen.getByRole('menuitem',{name:'Link'}))
    expect(screen.queryByRole('dialog')).not.toBeInTheDocument()
    expect(useEditorStore.getState().content).toBe(source)
    expect(screen.getByRole('status')).toHaveTextContent(/formatting boundary/)
  })
  it('balances formatting when the app menu inserts across a hidden delimiter',()=>{
    const source=wrap('A \\textbf{bold phrase} after.')
    useEditorStore.setState({content:source})
    const result=render(<VisualEditor/>),editor=view(result.container)
    act(()=>editor.dispatch({selection:{anchor:source.indexOf('phrase'),head:source.indexOf('after')+5}}))
    act(()=>window.dispatchEvent(new CustomEvent('editor:command',{detail:{command:'insert',text:'inserted'}})))
    expect(useEditorStore.getState().content).toBe(wrap('A \\textbf{bold inserted}.'))
  })
  it('inserts dependencies outside preamble comments',()=>{
    const source='\\documentclass{article}\n% \\begin{document}\n\\begin{document}\nHello.\n\\end{document}\n'
    useEditorStore.setState({content:source})
    const result=render(<VisualEditor/>),editor=view(result.container)
    act(()=>editor.dispatch({selection:{anchor:source.indexOf('Hello'),head:source.indexOf('Hello')+6}}))
    fireEvent.click(screen.getByTitle('Strikethrough'))
    expect(useEditorStore.getState().content).toBe(source.replace('\\begin{document}\nHello.','\\usepackage[normalem]{ulem}\n\\begin{document}\n\\sout{Hello.}'))
  })
  it('rejects edits during navigation',()=>{
    const result=render(<VisualEditor/>),editor=view(result.container)
    act(()=>useEditorStore.setState({isNavigating:true}))
    act(()=>editor.dispatch({changes:{from:0,to:5,insert:'Lost'}}))
    expect(editor.state.doc.toString()).toBe('Hello world.')
    expect(useEditorStore.getState().content).toBe('Hello world.')
  })
  it('edits math atomically, preserving inline delimiters',()=>{
    useEditorStore.setState({content:wrap('Energy $E = mc^2$ is useful.')})
    render(<VisualEditor/>)
    fireEvent.click(screen.getByRole('button',{name:'Edit math'}))
    fireEvent.change(screen.getByRole('textbox',{name:'Equation'}),{target:{value:'x^2'}})
    fireEvent.click(screen.getByRole('button',{name:'Apply'}))
    expect(useEditorStore.getState().content).toBe(wrap('Energy $x^2$ is useful.'))
    fireEvent.click(screen.getByTitle('Undo'))
    expect(useEditorStore.getState().content).toBe(wrap('Energy $E = mc^2$ is useful.'))
  })
  it('rejects a stale dialog after an agent edits the document',()=>{
    useEditorStore.setState({content:wrap('Energy $E = mc^2$.')})
    render(<VisualEditor/>)
    fireEvent.click(screen.getByRole('button',{name:'Edit math'}))
    fireEvent.change(screen.getByRole('textbox',{name:'Equation'}),{target:{value:'x^2'}})
    act(()=>useEditorStore.getState().setContent(wrap('An agent changed this.')))
    fireEvent.click(screen.getByRole('button',{name:'Apply'}))
    expect(useEditorStore.getState().content).toBe(wrap('An agent changed this.'))
    expect(screen.getByText(/document changed while/)).toBeVisible()
  })
  it('turns selected prose into a new equation',()=>{
    useEditorStore.setState({content:wrap('Use x squared here.')})
    const result=render(<VisualEditor/>),editor=view(result.container),source=editor.state.doc.toString(),from=source.indexOf('x squared')
    act(()=>editor.dispatch({selection:{anchor:from,head:from+9}}))
    fireEvent.pointerDown(screen.getByRole('button',{name:'Insert'}),{button:0,ctrlKey:false,pointerType:'mouse'})
    fireEvent.click(screen.getByRole('menuitem',{name:'Equation'}))
    fireEvent.click(screen.getByRole('button',{name:'Apply'}))
    expect(useEditorStore.getState().content).toContain('\\[\nx squared\n\\]')
  })

  it.each(['\\label{sec:old}','\\eqref{sec:old}','\\citep[see]{sec:old}'])('preserves the command and options when editing %s',original=>{
    useEditorStore.setState({content:wrap('Before '+original+' after.')})
    render(<VisualEditor/>)
    fireEvent.click(screen.getByRole('button',{name:'Edit reference'}))
    fireEvent.change(screen.getByRole('textbox'),{target:{value:'sec:new'}})
    fireEvent.click(screen.getByRole('button',{name:'Apply'}))
    expect(useEditorStore.getState().content).toBe(wrap('Before '+original.replace('sec:old','sec:new')+' after.'))
  })

})
